=============================
pygccxml.declarations package
=============================

This page contains the `pygccxml.declarations` package API documentation.

The :mod:`pygccxml.declarations` package
----------------------------------------

.. automodule:: pygccxml.declarations
    :members:
    :undoc-members:
    :show-inheritance:


The :mod:`algorithm <pygccxml.declarations.algorithm>` module
--------------------------------------------------------------

.. automodule:: pygccxml.declarations.algorithm
    :members:
    :show-inheritance:

The :mod:`algorithms_cache <pygccxml.declarations.algorithms_cache>` module
---------------------------------------------------------------------------

.. automodule:: pygccxml.declarations.algorithms_cache
    :members:
    :show-inheritance:

The :mod:`calldef <pygccxml.declarations.calldef>` module
---------------------------------------------------------

.. automodule:: pygccxml.declarations.calldef
    :members:
    :show-inheritance:

The :mod:`call_invocation <pygccxml.declarations.call_invocation>` module
-------------------------------------------------------------------------

.. automodule:: pygccxml.declarations.call_invocation
    :members:
    :show-inheritance:

The :mod:`class_declaration <pygccxml.declarations.class_declaration>` module
-----------------------------------------------------------------------------

.. automodule:: pygccxml.declarations.class_declaration
    :members:
    :show-inheritance:

The :mod:`compilers <pygccxml.declarations.compilers>` module
-------------------------------------------------------------

.. automodule:: pygccxml.declarations.compilers
    :members:
    :show-inheritance:

The :mod:`container_traits <pygccxml.declarations.container_traits>` module
---------------------------------------------------------------------------

.. automodule:: pygccxml.declarations.container_traits
    :members:
    :show-inheritance:

The :mod:`cpptypes <pygccxml.declarations.cpptypes>` module
-----------------------------------------------------------

.. automodule:: pygccxml.declarations.cpptypes
    :members:
    :show-inheritance:

The :mod:`declaration <pygccxml.declarations.declaration>` module
-----------------------------------------------------------------

.. automodule:: pygccxml.declarations.declaration
    :members:
    :show-inheritance:

The :mod:`decl_factory <pygccxml.declarations.decl_factory>` module
-------------------------------------------------------------------

.. automodule:: pygccxml.declarations.decl_factory
    :members:
    :show-inheritance:

The :mod:`decl_printer <pygccxml.declarations.decl_printer>` module
-------------------------------------------------------------------

.. automodule:: pygccxml.declarations.decl_printer
    :members:
    :show-inheritance:

The :mod:`decl_visitor <pygccxml.declarations.decl_visitor>` module
--------------------------------------------------------------------

.. automodule:: pygccxml.declarations.decl_visitor
    :members:
    :show-inheritance:

The :mod:`dependencies <pygccxml.declarations.dependencies>` module
--------------------------------------------------------------------

.. automodule:: pygccxml.declarations.dependencies
    :members:
    :show-inheritance:

The :mod:`enumeration <pygccxml.declarations.enumeration>` module
------------------------------------------------------------------

.. automodule:: pygccxml.declarations.enumeration
    :members:
    :show-inheritance:

The :mod:`function_traits <pygccxml.declarations.function_traits>` module
-------------------------------------------------------------------------

.. automodule:: pygccxml.declarations.function_traits
    :members:
    :show-inheritance:

The :mod:`matcher <pygccxml.declarations.matcher>` module
---------------------------------------------------------

.. automodule:: pygccxml.declarations.matcher
    :members:
    :show-inheritance:

The :mod:`matchers <pygccxml.declarations.matchers>` module
-----------------------------------------------------------

.. automodule:: pygccxml.declarations.matchers
    :members:
    :show-inheritance:

The :mod:`mdecl_wrapper <pygccxml.declarations.mdecl_wrapper>` module
---------------------------------------------------------------------

.. automodule:: pygccxml.declarations.mdecl_wrapper
    :members:
    :show-inheritance:

The :mod:`namespace <pygccxml.declarations.namespace>` module
-------------------------------------------------------------

.. automodule:: pygccxml.declarations.namespace
    :members:
    :show-inheritance:

The :mod:`scopedef <pygccxml.declarations.scopedef>` module
-----------------------------------------------------------

.. automodule:: pygccxml.declarations.scopedef
    :members:
    :show-inheritance:

The :mod:`templates <pygccxml.declarations.templates>` module
-------------------------------------------------------------

.. automodule:: pygccxml.declarations.templates
    :members:
    :show-inheritance:

The :mod:`typedef <pygccxml.declarations.typedef>` module
-----------------------------------------------

.. automodule:: pygccxml.declarations.typedef
    :members:
    :show-inheritance:

The :mod:`type_traits <pygccxml.declarations.type_traits>` module
-----------------------------------------------------------------

.. automodule:: pygccxml.declarations.type_traits
    :members:
    :show-inheritance:

The :mod:`type_visitor <pygccxml.declarations.type_visitor>` module
-------------------------------------------------------------------

.. automodule:: pygccxml.declarations.type_visitor
    :members:
    :show-inheritance:

The :mod:`variable <pygccxml.declarations.variable>` module
-----------------------------------------------------------

.. automodule:: pygccxml.declarations.variable
    :members:
    :show-inheritance:

